### ISSUE TITLE
Clean build failure (ubuntu 14.04 x64)

### ISSUE THREAD

**Issue by ooblahman** [tweag/HaskellR#212]
Compiling either at the base directory or in 'inline-r' gives the following linker error:

```
inline-r-0.7.1.0: build
inline-r-0.7.1.0: install
H-0.7.0.0: build
HaskellR-examples-0.1.0.0: build
ihaskell-inline-r-0.1.0.0: build
H-0.7.0.0: install
HaskellR-examples-0.1.0.0: install
Comple       
--  While building package ihaskell-inline-r-0.1.0.0 using:
      /home/user/.stack/programs/x86_64-linux/ghc-7.8.4/bin/runhaskell -package=Cabal-1.18.1.5 -clear-package-db -global-package-db -package-db=/home/user/.stack/snapshots/x86_64-linux/lts-2.14/7.8.4/pkgdb/ /tmp/stack18886/Setup.hs --builddir=.stack-work/dist/x86_64-linux/Cabal-1.18.1.5/ build --ghc-options -hpcdir .stack-work/dist/x86_64-linux/Cabal-1.18.1.5/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/user/alphasheets/HaskellR/.stack-work/logs/ihaskell-inline-r-0.1.0.0.log

    Building ihaskell-inline-r-0.1.0.0...
    Preprocessing library ihaskell-inline-r-0.1.0.0...
    /usr/bin/ld: .stack-work/dist/x86_64-linux/Cabal-1.18.1.5/build/IHaskell/Display/InlineR.dyn_o: relocation R_X86_64_PC32 against symbol `ihaskellzminlinezmrzm0zi1zi0zi0_IHaskellziDisplayziInlineR_rprint5_closure' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
```

This error consistently appears for all of the following, tested on multiple workstations:
- compiling external projects with 'inline-r' as a dependency in the Cabal file (works fine in Stack.yaml, but also needed in .cabal file for imports)
- compiling this repository at the base directory
- compiling just the 'inline-r' package

This makes it impossible to use HaskellR's functionality outside of the H interactive prompt. Is there anything else to the build process beyond 'stack build'? How would one include 'inline-r' in an external project and have it build without the link error?

**Comment by qnikst** [comment]
Hello, @ooblahman. Thanks for your report!

Could you, please, give some more information about how you are building your program?
I tried to write a simplest program in order to reproduce a problem and did following:

1. created a new project: `mkdir examples ; cabal init`
2. added dependency on `inline-r` to cabal file
3. created Main.hs with dummy contents (taken from http://tweag.github.io/HaskellR/docs/differences-repl-source.html )
4. run `stack init` in order to initialize `stack.yml`. It generated a file where I've added `inline-r-0.7.1.0` to extra deps
5. run stack build, and my program was built successfully
6. run program from ./stack-work/install/*/*/*/bin/examples and it worked.

Steps 4-5, could be changed to sandbox initialization, `cabal install --dependencies-only`, `cabal configure`, `cabal build` if you prefer cabal-install over stack. But result should be the same.

I'm asking this because according to logs the problem is in `ihaskell-inline-r`, that is not required to be build in order to use `inline-r` in your program and is needed only if you use `ihaskell`. We experiences problems with  `-fPIC` before, and seems few of them still alive, but those are related to `ihaskell` support and should not harm raw inline-r. We will take more precisely into that link error.

**Comment by mboes** [comment]
Use `stack build .` (note the dot) when in the `inline-r` directory to compile just that package.

For IHaskell support, the safest bet is to `stack --docker build` to build inside a docker image. But I'm surprised that you're getting linker errors given your distro, since it's the same one that's used as the base for HaskellR docker image.

**Comment by ooblahman** [comment]
Hey @qnikst, thanks for the reply. Just replicating your answer, and had a silly question -- I'm getting a parse error on the closing ']' in the quasiquotation. Is template-haskell or some other required explicitly as a dependency?

**Comment by mboes** [comment]
@ooblahman yes `{-# LANGUAGE QuasiQuotes #-}` is needed at the top. See the page linked page now.

**Comment by mboes** [comment]
Any LTS version should work, but best to test at first with the same LTS versions we test with, namely 2.14.

**Comment by ooblahman** [comment]
alright, I've narrowed down the problem -- the steps above replicate fine, but I get the linker error whenever I try to use inline-r as a dependency within a library (in the cabal file). The reproducing configuration is
```
name:                test
version:             0.1.0.0
synopsis:            Initial project template from stack
description:         Please see README.md
homepage:            http://github.com/githubuser/test#readme
license:             BSD3
license-file:        LICENSE
author:              Author name here
maintainer:          example@example.com
copyright:           2010 Author Here
category:            Web
build-type:          Simple
-- extra-source-files:
cabal-version:       >=1.10

library
  hs-source-dirs:      src
  exposed-modules:     Lib
  build-depends:       base >= 4.7 && < 5
                     , inline-r
  default-language:    Haskell2010

executable test-exe
  hs-source-dirs:      app
  main-is:             Main.hs
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  build-depends:       base
                     , test
                     , inline-r
  default-language:    Haskell2010

test-suite test-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs
  build-depends:       base
                     , test
                     , inline-r
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

source-repository head
  type:     git
  location: https://github.com/githubuser/test

```

**Comment by ooblahman** [comment]
bump? still having this issue and unable to resolve it. would greatly appreciate a diagnosis, as HaskellR is pretty great and we desperately need a better way to invoke R from Haskell than shell commands.

**Comment by mboes** [comment]
Can you paste the full error message when compiling the above test package? The first linker error you mentioned concerns ihaskell-inline-r, yet in the above .cabal you don't have ihaskell-inline-r as a dependency. So I would expect that you're getting a different error.

**Comment by ooblahman** [comment]
It's the same error as above, except the failing package is not ihaskell-inline-r, but the one I'm currently compiling, 'test':
```
test-0.1.0.0: configure
Configuring test-0.1.0.0...
test-0.1.0.0: build
Preprocessing library test-0.1.0.0...
/usr/bin/ld: .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Lib.dyn_o: relocation R_X86_64_PC32 against symbol `testzu2kZZ0y1f3EcZZLZZNPKvquIVd_Lib_someFunc7_closure' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

--  While building package test-0.1.0.0 using:
      /home/anand/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ build lib:test exe:test-exe --ghc-options  -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
```

**Comment by qnikst** [comment]
Ok, I've tried to test this problem container

1. I've started ubuntu-14.04, installed stack as described on https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md , installed libtinfo-dev, r-base-dev
2. Created a simple project with library and executable and tests using file you provided https://gist.github.com/qnikst/52aedf5c0989adf7bda7
3. run stack build and stack test, and I had success.

@ooblahman please could you check gist, and modify that in a way that it will start failing or does it fail for you as-is?

**Comment by mboes** [comment]
@ooblahman As I mentioned earlier, it's strange that you're getting a link error using this distro, because it's the base that the haskellr docker image uses too.

So we're no closer to the root cause, but as a workaround, you should try building everything in a docker container. That should be as easy as adding the following to the `stack.yaml` in your test project:
```
docker:
  enable: true
  repo: tweag/haskellr:latest
```

`stack build` and so on should work as usual.

**Comment by ooblahman** [comment]
thanks for the replies guys. @qnikst that gist fails to build for me as-is, but building in docker as per @mboes instructions works. Had one last question about the docker build process -- can I build in docker, then run on localhost? That is, do the binaries get copied over in ```stack install``` from the container to localhost, or do I always have to have docker running to execute the app?

**Comment by mboes** [comment]
@ooblahman I believe the resulting binaries get copied to the *host's* `~/.local/bin` by default when using `stack build --copy-bins` or `stack install` (the two commands are equivalent). The binaries have a good chance of working on the host, though given that the resulting library does have dynamically linked libraries, this is not a guarantee. `ldd <path/to/binary>` should show you what's dynamically linked.

If you do get to the bottom of this, we'd be very interested in including the reason and the workaround in the FAQ!

**Comment by qnikst** [comment]
@ooblahman in order to understand what is happening on your system, you may want to verify if you are using system ghc, or ghc loaded by stack, also afaiu this may happen if you use some special kernel. When I tried it in container I used ghc loaded by stack setup.

**Comment by ooblahman** [comment]
Looks like stack is using the ghc loaded using ```stack setup```. Just curious; if you've seen this ```recompile with -fPIC``` error in the past, is there a workaround by e.g. specifying ```-fPIC``` in ghc-options or something? Or, by using ```{-# OPTIONS_GHC -#}``` pragmas?

**Comment by ooblahman** [comment]
It appears building on docker images with stackage > lts-2.14 reproduces the issue. (e.g. building on a docker image identical to tweag/haskellr:latest except with lts-3.7).
