### ISSUE TITLE
Is there any way to support multithreaded operations?

### ISSUE THREAD

**Issue by ooblahman** [tweag/HaskellR#236]
I'm writing a webserver with concurrent access to the R interpreter (by using `runRegion` before main, and `forkIO`'ing at various later points). Every now and then, the server faults due to what I think are multithreading issues with HaskellR, e.g. `(png) too many devices open` and sometimes a good-old `segmentation fault`:

```
Warning: stack imbalance in '=', 39 then 36
Warning: stack imbalance in '{', 42 then 31
Warning: stack imbalance in '<-', 36 then 22
Error in as.raw(c(0x20, 0x69, 0x90, 0xb7, 0x55, 0x7f, 0x00, 0x00, 0x00,  : 
  bad value

./start_backend.sh: line 18:  7469 Segmentation fault 
```

and also:

```
7f258aa0f000-7f258aa13000 r--p 00063000 fd:01 938843                     /usr/local/lib/libzmq.so.5.
0.0
7f258aa13000-7f258aa14000 rw-p 00067000 fd:01 938843                     /usr/local/lib/libzmq.so.5.
0.0
7f258aa14000-7f258aa37000 r-xp 00000000 fd:01 393595                     /lib/x86_64-linux-gnu/ld-2.
19.so
7f258aa44000-7f258ac11000 rw-p 00000000 00:00 0 
7f258ac15000-7f258ac16000 rw-p 00000000 00:00 0 
7f258ac16000-7f258ac1d000 r--s 00000000 fd:01 944883                     /usr/lib/x86_64-linux-gnu/g
conv/gconv-modules.cache
7f258ac1d000-7f258ac1e000 r--p 00000000 fd:01 1317244                    /usr/lib/R/library/translat
ions/en/LC_MESSAGES/R.mo
7f258ac1e000-7f258ac36000 rw-p 00000000 00:00 0 
7f258ac36000-7f258ac37000 r--p 00022000 fd:01 393595                     /lib/x86_64-linux-gnu/ld-2$
19.so
7f258ac37000-7f258ac38000 rw-p 00023000 fd:01 393595                     /lib/x86_64-linux-gnu/ld-2$
19.so
7f258ac38000-7f258ac39000 rw-p 00000000 00:00 0 
7ffdd798f000-7ffdd79c6000 rw-p 00000000 00:00 0                          [stack]
7ffdd79fb000-7ffdd79fd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
./start_backend.sh: line 18: 17381 Aborted                 (core dumped) stack exec my-exe
```

The use case is a server which remotely executes user code against a common namespace. If I instead used `runRegion` anew in every sparked thread, I'd have to re-run code in all the other threads whenever a single thread changes. 

Is there any way to share the single interpreter instance provided by haskellR among multiple (haskell) threads?

**Comment by mboes** [comment]
R is not a reentrant library, which is why forks become impossible once you `runRegion`. So there's not much you can do here apart from serializing all accesses to R, e.g. by running R on the main thread (another R specificity: it doesn't like running on other threads), and then having the other Haskell threads delegate their R calls to this main thread. Would this fit your use case? There are alternatives, but when you say "executes user code against a common namespace" that makes me think this may well be the best way.

In fact we used to have a similar threading model internally in HaskellR, but with R spawned on a forked thread. This would cause problems so we removed it. But it's easy enough (and a more robust design) to build that on top of HaskellR, rather than internally.

**Comment by ooblahman** [comment]
Huh. Reading through the HaskellR docs, I see this:

> Arbitrary IO actions can be lifted into the R monad, including forkIO actions. But since forkIO can only fork IO actions, so long as withEmbeddedR is called only once at the beginning of the main function

But currently, I am calling `withEmbeddedR` before `main`, forking at various points, and invoking `runRegion` in those forks. I am able to observe true concurrent behavior (e.g. calling `Sys.sleep(10)` in one thread, and evaluating `1+1` in another thread). How does that work?

**Comment by qnikst** [comment]
Seems we need to update that part of documentation.  Behaviour did change since than, see  https://github.com/tweag/HaskellR/pull/189/files . As @mboes says previously we used a communication channel to serialize messages, but it had a number of problems. So now there is no serialization of the messages and you can make R execute code concurrently.

However you may have several problems:
1. R is not ready for concurrent calling of programs, with it's one thread can easily unprotect objects that are used in another thread, or use mutate some global state
2. If you R libraries are using thread local state, e.g. if you show GUI, that will not work as code will be executed from the context of the thread running R's code.

To run R in a forked thread you need to call `forkOS` and `withEmbeddedR` there, it will work unless you are using GUI on MacOS. In order to serialize messages you need to create a `*Chan` read messages in the "R"s thread, execute them and put result back.

I hope it helps.

**Comment by mboes** [comment]
> To run R in a forked thread you need to call forkOS and withEmbeddedR there, 

Let's please not recommend that. The R documentation explicitly says that running an R instance on anything else than the main thread is unsupported, and it screws up more than just event loops on OS X: it also confuses R's stack checks.

I'll update the documentation - that paragraph dates from before we removed the internal R interpreter thread.

> Amazing project by the way.

Thanks. :)

**Comment by ooblahman** [comment]
Thanks for updating the docs guys.

> 1. R is not ready for concurrent calling of programs, with it's one thread can easily unprotect objects that are used in another thread, or use mutate some global state

I assume this is because `runRegion` marks the objects in its region for deallocation when finished. Is it possible to place a declare a region whose objects are always protected? 

> 2. If you R libraries are using thread local state, e.g. if you show GUI, that will not work as code will be executed from the context of the thread running R's code.

In general, what precautions would be good to take when making concurrent R accesses? To elaborate on the use-case, I'm basically trying to write a multithreaded R kernel (as in, a jupyter-type kernel) with the following properties:
* sets of users can execute code (in, and against) various floating 'namespaces' 
* users can execute code concurrently (i.e. behaves like a true server)
It actually seems like using HaskellR (as opposed to building on IRkernel) is the best way to go.

**Comment by ooblahman** [comment]
Is it possible to check if an `SEXP` has been  protected by another thread, and not release the resource in the current thread if so?

**Comment by qnikst** [comment]
The problems with GC and concurrency are not related to inline-r, this is entirely R's part. R maintains an array for links to protected values, I doubt that it's thread safe in the first place, but even accesses to it are threadsafe, it's use is  not. Assume we have 2 functions, one allocates and protects some objects then another concurrent one allocates something, when former exists it will unprotect objects that were protected by the latter. Even if inline-r provide some additional protection on it's own, it's not possible to protect C part of the functions. So short answer R is not thread safe. So you'll have to serialize use of R kernels anyway..

**Comment by mboes** [comment]
> In general, what precautions would be good to take when making concurrent R accesses? 

I think your safest bet here, from the moment you want to share R's state between users, is to serialize all access, by running R on a single thread and then introduce

```Haskell
runOnR :: (forall s. R s a) -> ReaderT RChannel IO a
```

that will submit the given R computation over a channel to the R thread. R says it wants to always run on the main thread only, and doesn't want concurrent access from anyone. In practice of course you might be able to hack around that, much like we did when we first started HaskellR, just know that, in our experience, there be dragons. ;)

Since these are limitations of the R implementation, I think the would apply to IRkernel. But if you'd still like to try getting some amount of concurrency going, for performance reasons, we could share with you the knowledge we've accumulated about R's internals to point out what certainly won't work (i.e. what definitely needs a lock).

As @qnikst says, one particularly thorny issue is that if you have two users submitting computations C1, C2 to your server simultaneously, if either of those do any allocation during the computations then you're likely to run into race conditions due to concurrent modification of R's protection stack, which is involved in nearly all allocations. However, if you're willing to use a patched version of R there may be a reasonable way out.

**Comment by ooblahman** [comment]
The single-thread serialization solution is a no-go, since this kernel is intended for multiple client access. 

> But if you'd still like to try getting some amount of concurrency going, for performance reasons, we could share with you the knowledge we've accumulated about R's internals to point out what certainly won't work (i.e. what definitely needs a lock).

That'd be really great! I'd love to have a live call with you if you're up for it.

> However, if you're willing to use a patched version of R there may be a reasonable way out.

Would definitely like to hear your solution here.
