### ISSUE TITLE
tutorial gives the wrong argument to cast

### ISSUE THREAD

**Issue by aavogt** [tweag/HaskellR#247]
http://tweag.github.io/HaskellR/docs/casts-and-coercions.html has an expression that doesn't type check:

    (R.Int `R.cast` x)

This doesn't type check with either Int data constructor that is defined in the package. I think the `R.Int` should be `Foreign.R.Type.SInt`.

I think I would have been less confused if either (a) things weren't meant to be imported qualified / have the same name twice [which is probably too late to change at this point unfortunately] and/or (b) the contents of H.ghci were featured more prominently.

**Comment by mboes** [comment]
Thanks for the report. This typo in the documentation is now fixed by bf44217c05494111a436302c3fb875e4cff91d0b. In current master you can Note that in current `master` you can
```Haskell
H> SInt `cast` x
```
at the H prompt. Things aren't imported qualified in H any longer.

Regarding the contents of H.ghci, the only import it has is now:

```Haskell
import H.Prelude.Interactive as H.Prelude
```

Any suggestions as to how we could document this better?

**Comment by mboes** [comment]
Issue has been open for a while. Feel free to reopen if you can think of any further documentation fixes relevant to this issue.
