### ISSUE TITLE
inline-r build failure with ghc-8.4.4 (stackage lts-12.24)

### ISSUE THREAD

**Issue by kaizhang** [tweag/HaskellR#338]
/tmp/stack5459/inline-r-0.9.2/src/Data/Vector/SEXP.hs:374:15: error:
        Type family equation violates injectivity annotation.
        Type variable ‘s’ cannot be inferred from the right-hand side.
        In the type family equation:
          G.Mutable (W t ty s) = Mutable.W t ty
            -- Defined at src/Data/Vector/SEXP.hs:374:15
        |
    374 | type instance G.Mutable (W t ty s) = Mutable.W t ty
        |               ^^^^^^^^^

**Comment by kaizhang** [comment]
The problem may be that the `Mutable` type family becomes injective in vector-0.12.0.2.

**Comment by qnikst** [comment]
Thanks! I'll take a look into this problem

**Comment by qnikst** [comment]
It's very unfortunate that vector did that update in `0.0.0.x` version, for now, I'll put a new revision on hackage that will set an upper boundary on vector, and try to update our API later.

**Comment by cartazio** [comment]
I’m sorry about the change breaking y’all, the maintainers of vector collectively (both past and present) have never seen a non injective instance of the vector type classes before.. thus I had back ported it into a bug fix because improved type inference never breaks anything :)))))) ).  None the less, it is my fault and I apologize.  Though injective type families are here to stay in all future releases of vector.  


It does look like the design fix on the Haskell r side would be to carry the type reflection param in the mutable vector values too. This does seem necessary if you want good type inference in the presence of using thaw and freeze at least.

**Comment by qnikst** [comment]
@cartazio thanks for the comment! I think this is a good fix, just haskell-r have not been ready by that.
I'll take a look at this change and will use a new vector interface, after fixing one more urgent bug I'm fighting with for the last few weeks.

**Comment by cartazio** [comment]
Glad to hear we’re on the same page overall. And that as someone more familiar with the inline R package, my guesstimate on the design fix isn’t off target.  

Merry triage and thanks for not being too miffed :)

**Comment by djsamperi** [comment]
Do you think this issue might be related to the GHC non-termination reported in bug #16109? If so, then fixing this may fix the non-termination issue too. 

BTW, is there a way to view/print the parse tree that is returned by Language.R.QQ.parse in the R quasiquoter (with ghc option -ddump-splices)?

**Comment by qnikst** [comment]
I think the issue here is simper, basically in vector you have a relation (some details may be wrong typing from phone, from my memory, but the idea should be correct)

type instance PureVector = MutableVector

PureVector "hides" it's value type, and MutableVector - monad where it's being mutated and value type. That is needed because we can mutated vector in any primitive monad and freeze such vector from any primitive monad.
In inline-r we have an additional restriction even pure vector should be bound to the resource context, as it uses R memory that lives in a stacked context. So it looks like (leaving unrelated thing)
```
type instance G.Vector (Vector s) = M.Vector
```
note that there is `s` on the left but no `s` on the right - why because can no longer use any primitive monad, we should keep context where we can protect our values from R's GC.

The vector authors decided that you should be able to infer immutable type from the mutable type, that looks very sane based on the vector library desing and is consistent; more over it can help from so very complicated errors. So the premise, seeing a right part of the equation you must be able to infer the left part.

But what we see in inline-r: G.Mutable -> ...., and on the left side there is `s` that doesn't exist on the right. So we can't infer that - we broke the promise imposed on us by the library.

So the solution should be to keep `s` on the right hand side as well. I've started working on that yesterday but didn't finish, at this moment I expect that the change may be large but it's for good.

**Comment by qnikst** [comment]
Wrt QQ, I usually add -ddump-simpl to the `--ghc-options` in either cabal or stack, together with `-ddump-to-file`. Then I find files in dist-newbuild or .stack-work respectively

**Comment by cartazio** [comment]
Alex: you anticipate the change ultimately improving the inline-r user
experience? That’s great to hear !

**Comment by qnikst** [comment]
@cartazio for me as the inline-r maintainer this change is pretty annoying :), because we've found a nice spot in the vector design where we were able to fit the our guarantees. But, `inline-r` doesn't use vector API in the common way, so I'm not surprised that solutions that are good for the `vector` may be problematic for us. And I think for `vector` itself the change makes total sense.

At least I think it's good that it requires me to recheck guarantees we provide in `inline-r` and find another sweet spot.

**Comment by cartazio** [comment]
I do hope injectivity does improve inference for all users ultimately.

I do have a nonstandard example myself where I had to fix stuff up after adding infectivity (i had to make some of my own type families injective) https://github.com/wellposed/numerical/blob/master/src/Numerical/Data/Vector/HPair.hs#L60-L106
(that module gives me SOA format vectors where I can use different underlying vector representations at the leaves)

**Comment by djsamperi** [comment]
Thanks for the feedback. On the -ddump-simpl bit, the output dump is interesting, but it does not include what I was looking for: a pretty-printed rendering of the parse tree that R sees (a pointer to this tree appears in the simplified output, but not the tree itself). Of course, the parse tree can easily be obtained by using tools on the R side, so this is just a consistency check. A related question: is there a way to show/print the R-side SEXP structure used to represent the object pointed to by [r|expr|], instead of showing the printR output? Perhaps hexp can be used for this purpose?

**Comment by qnikst** [comment]
@djsamperi  `hexp` and `Matcher` can be used to traverse a tree, though if you don't need to test that on the Haskell side it's better to use debug output of the R itself because you need special care as some structures contain loops. I can try to search in our inline-r codebase the examples of such traversals and add that to the library. But, please, create a separate issue for that and let's keep this one for the injectivity, otherwise, it would be painfully hard to find this conversation again.

**Comment by qnikst** [comment]
The original issue is fixed in `inline-r-0.10` thanks for the patience.
